name = "ratemybench-worker"
main = "src/index.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-11-11"

kv_namespaces = [
  { binding = "BENCHES_KV", id = "66a5099461f945cfb6843ab6a59d090c", preview_id = "815888bfd28a4216b19b00227a15f4bb" }
]

send_email = [
    {name = "REVIEW_EMAIL_ADDRESS", destination_address = "review@ratemybench.vaines.org"},
]

[observability]
enabled = true

[vars]
# AUTH_TOKEN="" # Encrypted secret in the console
